//
// Created by 444 on 09.12.2020.
//

#ifndef LABA5_ACCOUNTTYPE_H
#define LABA5_ACCOUNTTYPE_H
enum AccountType {
    DEBIT_ACCOUNT,DEPOSIT_ACCOUNT,CREDIT_ACCOUNT
};
#endif //LABA5_ACCOUNTTYPE_H
